// Plural utility globally scoped for access by translation functions
window.ruPlural = function(n, one, few, many) {
  const mod10 = n % 10, mod100 = n % 100;
  if (mod10 === 1 && mod100 !== 11) return one;
  if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return few;
  return many;
};

window.POSITIONS_RU = {
  0: "0 · До описания персонажа",
  1: "1 · После описания персонажа",
  2: "2 · До примеров сообщений",
  3: "3 · После примеров сообщений",
  4: "4 · Верх авторских заметок",
  5: "5 · Низ авторских заметок",
  "6:0": "6 · @ Depth — System",
  "6:1": "6 · @ Depth — User",
  "6:2": "6 · @ Depth — Assistant",
  7: "7 · Outlet",
};

window.WARN_I18N = window.WARN_I18N || {};
window.WARN_I18N.ru = {
  heading: "⚠ Заметки о конвертации",
  nonDefaultPos: (n) => "<strong>" + n + " " + ruPlural(n, "запись", "записи", "записей") + "</strong> используют нестандартные позиции — они будут удалены в JAI.",
  stickyDropped: "Найдены записи-«липучки» (Sticky) — они будут удалены (аналога в JAI нет).",
  vectorizedDropped: "Найдены векторизованные записи — JAI использует только совпадение по ключевым словам.",
  jaiPosSet: "Для всех записей выставлена позиция <strong>Перед описанием персонажа (0)</strong>. При необходимости измените её в ST.",
  scriptMerged: "Записи скрипта объединены в <strong>одну запись ST</strong> в выбранной позиции Scenario.",
  scriptSplit: "Каждая запись скрипта создаёт до <strong>2 записей ST</strong> (scenario + personality). При необходимости измените позиции в панели выше.",
  outletReminder: "Для всех записей, привязанных к позиции <strong>7 / Outlet</strong>, добавьте <code>{{outlet::name}}</code> в карточку персонажа.",
  filtersUsed: (n) => "<strong>" + n + " " + ruPlural(n, "запись", "записи", "записей") + "</strong> используют фильтры — они сопоставлены с дополнительными ключами (secondary) в ST.",
  ifChainDup: "Скрипты if-chain могут содержать повторяющиеся наборы ключевых слов. Они сгруппированы в категорию <strong>If-Chain</strong>.",
  scriptSecurity: "<strong>Примечание по безопасности:</strong> Скрипты выполняются локально в вашем браузере. Загружайте их только из надёжных источников.",
  dynLoreInlined: (n) => "<strong>" + n + " " + ruPlural(n, "запись-триггер", "записи-триггера", "записей-триггеров") + "</strong> (по тегу, без ключевых слов) объединены с записью, которая испускает этот тег — в ST нет межзаписевой системы тегов, поэтому если тег испускают две записи, этот текст может появиться дважды за один ход вместо одного раза.",
  dynLoreShifts: (n) => "<strong>" + n + " " + ruPlural(n, "Shift", "Shift'а", "Shift'ов") + "</strong> стали отдельными записями ST с условием AND ALL по ключевым словам родителя — приближение к «только после срабатывания родителя».",
  dynLoreGates: (n) => "<strong>" + n + " " + ruPlural(n, "запись", "записи", "записей") + "</strong> использовали условия, которые ST не может выразить (теги, эмоции, maxMessages, notAll или таргетинг prev.*) — эти условия были отброшены; логика ключевых слов и приоритета сохраняется.",
  dynLoreNameBlock: (n) => "<strong>" + n + " " + ruPlural(n, "запись nameBlock", "записи nameBlock", "записей nameBlock") + "</strong> сопоставлены с фильтром персонажа ST (исключение).",
  dynLoreRelationships: (n) => "<strong>" + n + " " + ruPlural(n, "триггер отношений", "триггера отношений", "триггеров отношений") + "</strong> преобразованы в записи, требующие оба имени персонажей (AND ALL) — исходное условие requireTags сохранить не удалось.",
  scriptRepaired: (s) => {
    const parts = [];
    if (s.unclosedStrings) parts.push(s.unclosedStrings + " " + ruPlural(s.unclosedStrings, "незакрытая строка", "незакрытые строки", "незакрытых строк"));
    if (s.missingCommas) parts.push(s.missingCommas + " " + ruPlural(s.missingCommas, "пропущенная запятая", "пропущенные запятые", "пропущенных запятых") + " между элементами списка");
    if (s.prematureCloses) parts.push(s.prematureCloses + " " + ruPlural(s.prematureCloses, "преждевременно закрытый массив", "преждевременно закрытых массива", "преждевременно закрытых массивов") + ", из-за чего часть записей осталась «снаружи»");
    return "<strong>Автоматически исправлено " + parts.length + " " + ruPlural(parts.length, "синтаксическая ошибка", "синтаксические ошибки", "синтаксических ошибок") + "</strong> в скрипте, чтобы его вообще можно было разобрать: " + parts.join(", ") + ". Проверьте, что затронутые записи собрались верно.";
  }
};

window.BADGE_I18N = window.BADGE_I18N || {};
window.BADGE_I18N.ru = {
  cannotDetect: () => "Не удалось определить формат. Перетащите корректный файл ST/JAI или вставьте текст/скрипт.",
  scriptParseFailed: (msg) => "Ошибка разбора скрипта: " + msg,
  noEntriesLoreEntries: () => "В loreEntries не найдено записей.",
  detectedLoreEntries: (n) => "Обнаружен <strong>скрипт loreEntries</strong> — " + n + " " + ruPlural(n, "запись", "записи", "записей") + ". Настройте параметры выше и снова нажмите «Конвертировать».",
  detectedDynamicLore: (n) => "Обнаружен <strong>Advanced Lore Script</strong> — " + n + " " + ruPlural(n, "запись", "записи", "записей") + " (после разворачивания Shifts/триггеров). Настройте параметры выше и снова нажмите «Конвертировать».",
  ifChainParseFailed: (msg) => "Ошибка разбора if-chain: " + msg,
  noKeywordEntries: () => "Не найдено записей на основе ключевых слов. Убедитесь, что скрипт использует lastMessage.includes(…) и context.character.personality/scenario +=",
  detectedIfChain: (n) => "Обнаружен <strong>скрипт if-chain</strong> — " + n + " " + ruPlural(n, "блок", "блока", "блоков") + ". Настройте параметры выше и снова нажмите «Конвертировать».",
  noEntriesFound: () => "Записи не найдены.",
  detectedStWi: (n) => "Обнаружено <strong>ST World Info</strong> — " + n + " " + ruPlural(n, "запись", "записи", "записей") + " → JAI JSON",
  detectedJai: (n) => "Обнаружено <strong>JAI Lorebook JSON</strong> — " + n + " " + ruPlural(n, "запись", "записи", "записей") + " → ST World Info",
  convertedScript: (n, m) => "Конвертировано <strong>" + n + " " + ruPlural(n, "запись скрипта", "записи скрипта", "записей скрипта") + "</strong> → <strong>" + m + " " + ruPlural(m, "запись ST", "записи ST", "записей ST") + "</strong>",
  extractingDocx: () => "Извлечение JSON/кода из DOCX...",
  docxReadFailed: (msg) => "Не удалось прочитать DOCX: " + msg,
  nothingToConvert: () => "Нечего конвертировать — вставьте текст или перетащите файл.",
  fileLoaded: (name) => "✓ загружено: " + name,
};

window.I18N = window.I18N || {};
window.I18N.ru = {
  runeLine: "Алхимия Томов",
  title: "Конвертер Лорбуков",
  subtitle: "SillyTavern World Info \u00A0⇄\u00A0 JanitorAI Lorebook и скрипты",
  importLabel: "Импорт",
  pillSt: "ST World Info JSON",
  pillJai: "JAI Lorebook JSON",
  pillJs: "Скрипт loreEntries",
  pillChain: "Скрипт if-chain",
  pillTitle: "Нажмите, чтобы загрузить небольшой пример этого формата",
  pillsHint: "Не уверены, какой у вас формат? Нажмите на плашку выше, чтобы увидеть пример.",
  dropLabel: "Перетащите сюда файл лорбука",
  dropSub: "ST JSON · JAI JSON · скрипты (.txt .js .json .docx)",
  pasteInputPh: "Вставьте сюда любой формат:\nST World Info      →  {\"entries\":{\"0\":{…}}}\nJAI JSON           →  [{…},{…}]\nloreEntries script →  const loreEntries = [{…}]\nif-chain script    →  if (lastMessage.includes('kw')) { context.character… }",
  lbNameLabel: "Название лорбука",
  lbNamePh: "напр. Мой Лорбук (используется как имя файла)",
  outletNameLabel: "Имя Outlet",
  outletNameSub: "(для записей personality)",
  outletNamePh: "напр. char_knowledge",
  outletNameTitle: "Записи в позиции 7 появятся, только если в карточке персонажа есть {{outlet::this_name}}. Оставьте пустым, чтобы сгенерировать имя автоматически из названия лорбука.",
  catTitle: "Позиции записей по категориям",
  catNote: "Personality по умолчанию — 7 / Outlet",
  cgCategory: "Категория",
  cgScenarioPos: "Позиция Scenario",
  cgPersonalityPos: "Позиция Personality",
  advTitle: "Расширенные настройки скрипта",
  mergeTitle: "Выкл: каждая запись скрипта превращается в до двух записей ST (одна для текста scenario, одна для personality). Вкл: они объединяются в одну запись, помещённую в позицию Scenario.",
  mergeLabel: "Объединить Scenario и Personality в одну запись (использует позицию Scenario)",
  scenPrefixLabel: "Префикс текста Scenario",
  prefixNewlineNote: "(используйте \\n для переноса строки)",
  scenPrefixPh: "напр. [Scenario]\\n",
  persPrefixLabel: "Префикс текста Personality",
  persPrefixPh: "напр. [Personality]\\n",
  convertBtn: "Конвертировать ⟶",
  clearBtn: "Очистить",
  fieldMapSummary: "Справка по соответствию полей",
  fmScriptsSt: "Скрипты → ST",
  fmEntry: "entry",
  fmEntryVal: "до 2 записей ST (или 1 объединённая)",
  fmScenText: "текст scenario",
  fmScenTextVal: "содержимое, позиция по умолчанию 0 или 1",
  fmPersText: "текст personality",
  fmPersTextVal: "содержимое, позиция 7 / Outlet (по умолчанию)",
  fmKeywordsVal: "key (общее)",
  fmPriority: "priority × 10",
  fmOrder: "order",
  fmDelay: "delay",
  fmNotWith: "keysecondary + NOT ANY (2)",
  fmRequiresAny: "keysecondary + AND ANY (0)",
  fmRequiresAll: "keysecondary + AND ALL (1)",
  fmUniversal: "ST ↔ JAI JSON (универсально)",
  fmUniversalVal: "keyword(s) / enabled / minMessages",
  fmPositionsHead: "Позиции",
  fmPos0: "↑ до описания персонажа",
  fmPos1: "↓ после описания персонажа",
  fmPos2: "↑ до примеров сообщений",
  fmPos3: "↓ после примеров сообщений",
  fmPos4: "↑ верх авторских заметок",
  fmPos5: "↓ низ авторских заметок",
  fmPos6: "@ Depth (System/User/Asst + номер глубины)",
  fmPos7: "Outlet (нужен {{outlet::name}} в карточке)",
  resultsDivider: "Результат",
  rCountLabel: "Исходных записей:",
  rSTLabel: "Записей ST на выходе:",
  rSrcLabel: "Формат:",
  previewNote1: "* Таблица показывает предпросмотр. Настройте категории или параметры выше и нажмите",
  convertBtnPlain: "Конвертировать ⟶",
  previewNote2: "чтобы сгенерировать JSON.",
  thNum: "#",
  thType: "Тип",
  thName: "Имя",
  thKeywords: "Ключевые слова",
  thSecondary: "Доп.",
  thPos: "Поз.",
  thOrder: "Order",
  thDelay: "Delay",
  outputJsonLabel: "JSON на выходе",
  copyBtn: "копировать",
  downloadBtn: "Скачать JSON",
  footerLine1: "Вся обработка выполняется локально — ничего не покидает ваш браузер.",
  footerStDocs: "Документация ST",
  footerJaiScripts: "Скрипты JAI",
  pmTitle: "Предпросмотр записи",
  themeDark: "🌙 Тёмная",
  themeLight: "☀ Светлая",
  modeSimple: "Простой",
  modeAdvanced: "Расширенный",
  modeHintSimple: "Простой режим: перетащите файл, нажмите «Конвертировать», скачайте результат. Переключитесь на «Расширенный», чтобы настроить позиции категорий, префиксы и увидеть сырой JSON.",
  modeHintAdvanced: "Расширенный режим: полный контроль над позициями категорий, префиксами скрипта, объединением записей и сырым JSON на выходе.",
};