window.POSITIONS = {
  0: "0 · Before Char Defs",
  1: "1 · After Char Defs",
  2: "2 · Before Example Msgs",
  3: "3 · After Example Msgs",
  4: "4 · Top of AN",
  5: "5 · Bottom of AN",
  "6:0": "6 · @ Depth — System",
  "6:1": "6 · @ Depth — User",
  "6:2": "6 · @ Depth — Assistant",
  7: "7 · Outlet",
};

window.WARN_I18N = window.WARN_I18N || {};
window.WARN_I18N.en = {
  heading: "⚠ Conversion notes",
  nonDefaultPos: (n) => "<strong>" + n + " entries</strong> use non-default positions — dropped in JAI.",
  stickyDropped: "Sticky entries found — dropped (no JAI equivalent).",
  vectorizedDropped: "Vectorized entries found — JAI uses keyword matching only.",
  jaiPosSet: "Position set to <strong>Before Char (0)</strong> for all entries. Adjust in ST as needed.",
  scriptMerged: "Script entries merged into a <strong>single ST entry</strong> at the chosen Scenario position.",
  scriptSplit: "Each script entry generates up to <strong>2 ST entries</strong> (scenario + personality). Adjust positions in the panel if needed.",
  outletReminder: "For any entries mapped to <strong>7 / Outlet</strong>, make sure to add <code>{{outlet::name}}</code> to your character card.",
  filtersUsed: (n) => "<strong>" + n + " entries</strong> use filters — mapped to ST secondary keys.",
  ifChainDup: "If-chain scripts may have duplicate keyword sets. They have been grouped under the <strong>If-Chain</strong> category.",
  scriptSecurity: "<strong>Security Note:</strong> Scripts are evaluated locally in your browser. Only import scripts from trusted sources.",
  dynLoreInlined: (n) => "<strong>" + n + " trigger-only entr" + (n === 1 ? "y" : "ies") + "</strong> (tag-based, no keywords) " + (n === 1 ? "was" : "were") + " merged into whichever entry emits its tag — ST has no cross-entry tag system, so if two entries share a trigger tag, that content may now appear twice in the same turn instead of once.",
  dynLoreShifts: (n) => "<strong>" + n + " Shift" + (n === 1 ? "" : "s") + "</strong> became separate ST entries gated on the parent's keywords via AND ALL — an approximation of \"only after the parent fires.\"",
  dynLoreGates: (n) => "<strong>" + n + " entr" + (n === 1 ? "y" : "ies") + "</strong> used gates ST can't express (tag-gates, emotion detection, maxMessages, notAll, or prev.* targeting) — those conditions were dropped; keyword/priority logic still applies.",
  dynLoreNameBlock: (n) => "<strong>" + n + " nameBlock entr" + (n === 1 ? "y" : "ies") + "</strong> mapped to ST's Character Filter (exclude).",
  dynLoreRelationships: (n) => "<strong>" + n + " relationship injection" + (n === 1 ? "" : "s") + "</strong> converted to entries requiring both characters' names (AND ALL) — the original requireTags condition couldn't be preserved.",
  scriptRepaired: (s) => {
    const parts = [];
    if (s.unclosedStrings) parts.push(s.unclosedStrings + " unclosed string" + (s.unclosedStrings === 1 ? "" : "s"));
    if (s.missingCommas) parts.push(s.missingCommas + " missing comma" + (s.missingCommas === 1 ? "" : "s") + " between list items");
    if (s.prematureCloses) parts.push(s.prematureCloses + " array" + (s.prematureCloses === 1 ? "" : "s") + " that got closed early, orphaning entries after it");
    return "<strong>Auto-repaired " + parts.length + " syntax issue" + (parts.length === 1 ? "" : "s") + "</strong> in your script so it could still parse: " + parts.join(", ") + ". Double-check the affected entries came through correctly.";
  }
};

window.BADGE_I18N = window.BADGE_I18N || {};
window.BADGE_I18N.en = {
  cannotDetect: () => "Cannot detect format. Drop a valid ST/JAI file or valid text/script.",
  scriptParseFailed: (msg) => "Script parse failed: " + msg,
  noEntriesLoreEntries: () => "No entries found in loreEntries.",
  detectedLoreEntries: (n) => "Detected <strong>loreEntries Script</strong> — " + n + " entr" + (n === 1 ? "y" : "ies") + ". Set options above, then click Convert again.",
  detectedDynamicLore: (n) => "Detected <strong>Advanced Lore Script</strong> — " + n + " entr" + (n === 1 ? "y" : "ies") + " (after flattening Shifts/triggers). Set options above, then click Convert again.",
  ifChainParseFailed: (msg) => "if-chain parse failed: " + msg,
  noKeywordEntries: () => "No keyword-based entries found. Check the script uses lastMessage.includes(…) and context.character.personality/scenario +=",
  detectedIfChain: (n) => "Detected <strong>if-chain Script</strong> — " + n + " blocks. Set options above, then click Convert again.",
  noEntriesFound: () => "No entries found.",
  detectedStWi: (n) => "Detected <strong>ST World Info</strong> — " + n + " entr" + (n === 1 ? "y" : "ies") + " → JAI JSON",
  detectedJai: (n) => "Detected <strong>JAI Lorebook JSON</strong> — " + n + " entr" + (n === 1 ? "y" : "ies") + " → ST World Info",
  convertedScript: (n, m) => "Converted <strong>" + n + " script entries</strong> → <strong>" + m + " ST entries</strong>",
  extractingDocx: () => "Extracting JSON/Code from DOCX...",
  docxReadFailed: (msg) => "DOCX Read Failed: " + msg,
  nothingToConvert: () => "Nothing to convert — paste or drop a file first.",
  fileLoaded: (name) => "✓ loaded: " + name,
};

window.I18N = window.I18N || {};
window.I18N.en = {
  runeLine: "Tome Alchemy",
  title: "Lorebook Converter",
  subtitle: "SillyTavern World Info \u00A0⇄\u00A0 JanitorAI Lorebook & Scripts",
  importLabel: "Import",
  pillSt: "ST World Info JSON",
  pillJai: "JAI Lorebook JSON",
  pillJs: "loreEntries Script",
  pillChain: "if-chain Script",
  pillTitle: "Click to load a tiny example of this format",
  pillsHint: "Not sure which format you have? Click a pill above to see a sample.",
  dropLabel: "Drop any lorebook file here",
  dropSub: "ST JSON · JAI JSON · scripts (.txt .js .json .docx)",
  pasteInputPh: "Paste any format here:\nST World Info      →  {\"entries\":{\"0\":{…}}}\nJAI JSON           →  [{…},{…}]\nloreEntries script →  const loreEntries = [{…}]\nif-chain script    →  if (lastMessage.includes('kw')) { context.character… }",
  lbNameLabel: "Lorebook name",
  lbNamePh: "e.g. My Lorebook (used as filename)",
  outletNameLabel: "Outlet name",
  outletNameSub: "(for personality entries)",
  outletNamePh: "e.g. char_knowledge",
  outletNameTitle: "Entries at position 7 only show up if your character card contains {{outlet::this_name}} somewhere in it. Leave blank to auto-generate one from the lorebook name.",
  catTitle: "Entry positions by category",
  catNote: "Personality defaults to 7 / Outlet",
  cgCategory: "Category",
  cgScenarioPos: "Scenario Pos",
  cgPersonalityPos: "Personality Pos",
  advTitle: "Advanced Script Settings",
  mergeTitle: "Off: each script entry becomes up to two ST entries (one for scenario text, one for personality text). On: they're combined into one entry, placed at the Scenario position.",
  mergeLabel: "Merge Scenario & Personality into a single entry (uses Scenario position)",
  scenPrefixLabel: "Scenario text prefix",
  prefixNewlineNote: "(use \\n for newline)",
  scenPrefixPh: "e.g. [Scenario]\\n",
  persPrefixLabel: "Personality text prefix",
  persPrefixPh: "e.g. [Personality]\\n",
  convertBtn: "Convert ⟶",
  clearBtn: "Clear",
  fieldMapSummary: "Field mapping reference",
  fmScriptsSt: "Scripts → ST",
  fmEntry: "entry",
  fmEntryVal: "up to 2 ST entries (or 1 merged)",
  fmScenText: "scenario text",
  fmScenTextVal: "content, mapped position (default 0 or 1)",
  fmPersText: "personality text",
  fmPersTextVal: "content, position 7 / Outlet (default)",
  fmKeywordsVal: "key (shared)",
  fmPriority: "priority × 10",
  fmOrder: "order",
  fmDelay: "delay",
  fmNotWith: "keysecondary + NOT ANY (2)",
  fmRequiresAny: "keysecondary + AND ANY (0)",
  fmRequiresAll: "keysecondary + AND ALL (1)",
  fmUniversal: "ST ↔ JAI JSON (universal)",
  fmUniversalVal: "keyword(s) / enabled / minMessages",
  fmPositionsHead: "Positions",
  fmPos0: "↑Char",
  fmPos1: "↓Char",
  fmPos2: "↑Ex Msgs",
  fmPos3: "↓Ex Msgs",
  fmPos4: "↑AN",
  fmPos5: "↓AN",
  fmPos6: "@ Depth (System/User/Asst + depth number)",
  fmPos7: "Outlet (needs {{outlet::name}} in card)",
  resultsDivider: "Results",
  rCountLabel: "Source entries:",
  rSTLabel: "ST entries out:",
  rSrcLabel: "Format:",
  previewNote1: "* Table is showing a live preview. Adjust categories or settings above and click",
  convertBtnPlain: "Convert ⟶",
  previewNote2: "to generate your JSON.",
  thNum: "#",
  thType: "Type",
  thName: "Name",
  thKeywords: "Keywords",
  thSecondary: "Secondary",
  thPos: "Pos",
  thOrder: "Order",
  thDelay: "Delay",
  outputJsonLabel: "Output JSON",
  copyBtn: "copy",
  downloadBtn: "Download JSON",
  footerLine1: "All processing is local — nothing leaves your browser.",
  footerStDocs: "ST Docs",
  footerJaiScripts: "JAI Scripts",
  pmTitle: "Entry Preview",
  themeDark: "🌙 Dark",
  themeLight: "☀ Light",
  cardEditorLabel: "Card Editor",
  cardEditorTitle: "Create an ST character card",
  cardEditorMirrorLabel: "mirror",
  cardEditorMirrorTitle: "Backup link if the main one is down",
  modeSimple: "Simple",
  modeAdvanced: "Advanced",
  modeHintSimple: "Simple mode: drop your file, hit Convert, download. Switch to Advanced for category positions, prefixes, and the raw JSON.",
  modeHintAdvanced: "Advanced mode: full control over category positions, script prefixes, merge behavior, and the raw JSON output.",
};